# Generated by Django 5.1.1 on 2024-09-08 13:08

import django.db.models.deletion
import django_resized.forms
import djrichtextfield.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('ingredients', djrichtextfield.models.RichTextField(max_length=10000)),
                ('instructions', djrichtextfield.models.RichTextField(max_length=10000)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='recipes/')),
                ('image_alt', models.CharField(max_length=100)),
                ('my_recipes', models.CharField(choices=[('my_recipes', 'My Recipes'), ('saved_recipes', 'My Saved Recipes'), ('create_recipe', 'Create New Recipe')], max_length=50)),
                ('saved_recipes', models.CharField(max_length=50)),
                ('create_recipe', djrichtextfield.models.RichTextField(max_length=10000)),
                ('posted_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
    ]
