# Generated by Django 5.1.1 on 2024-09-13 19:43

import django.utils.timezone
import djrichtextfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recipes",
            "0003_remove_recipe_my_recipes_remove_recipe_saved_recipes_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={},
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="posted_date",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="calories",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="cuisine_types",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="meal_type",
        ),
        migrations.AddField(
            model_name="recipe",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=djrichtextfield.models.RichTextField(max_length=10000),
        ),
    ]
