# Generated by Django 5.1.1 on 2024-09-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_recipe_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
