# Generated by Django 5.1.1 on 2024-09-20 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_review_favorite_follow"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
