# Generated by Django 5.1.1 on 2025-01-05 01:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_alter_favorite_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_recipes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]

