# Generated by Django 5.1.1 on 2025-01-13 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0012_recipe_average_rating_alter_review_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="average_rating",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="likes",
        ),
        migrations.DeleteModel(
            name="Favorite",
        ),
    ]
