# Generated by Django 5.1.1 on 2025-01-14 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0013_remove_recipe_average_rating_remove_recipe_likes_and_more"), ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="rating",
        ),
        migrations.AlterField(
            model_name="review",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="recipes.recipe",
            ),
        ),
    ]
