# Generated by Django 5.1.1 on 2025-01-19 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0014_remove_review_rating_alter_review_recipe"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Favourite",
            fields=[
                ("id",
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name="ID",
                 ),
                 ),
                ("created_at",
                 models.DateTimeField(
                     auto_now_add=True)),
                ("recipe",
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to="recipes.recipe"),
                 ),
                ("user",
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to=settings.AUTH_USER_MODEL,
                 ),
                 ),
            ],
        ),
    ]
